# Generated by Django 5.1.1 on 2024-10-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_category_options_alter_flowers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='image',
            field=models.ImageField(default=2, upload_to='flowers/'),
            preserve_default=False,
        ),
    ]
