# Generated by Django 5.1.1 on 2024-10-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_flowers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='flowerstype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flowers_type/'),
        ),
    ]
