# Generated by Django 5.1.1 on 2024-10-08 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_category_image_alter_flowerstype_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flowers', to='data.category'),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='flowers_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flowers', to='data.flowerstype'),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flowers', to=settings.AUTH_USER_MODEL),
        ),
    ]
