# Generated by Django 5.1.1 on 2024-10-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_categorytype_options_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
    ]
