# Generated by Django 5.1.1 on 2024-10-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuser',
            name='desc',
            field=models.TextField(default=2, max_length=3000),
            preserve_default=False,
        ),
    ]
