# Generated by Django 5.1.1 on 2024-10-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_abstractuser_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuser',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
